# Generated by Django 6.0.6 on 2026-06-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_order_cart_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
