# Generated by Django 6.0.6 on 2026-06-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_remove_category_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="first_name",
            new_name="guest_name",
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
